version: '3.9'

services:

  db:
    image: postgres:16.2
    restart: always
    shm_size: 128 mb
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: local_db
  
  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
