"""empty message

Revision ID: caafd3e9317a
Revises: 7c7431c1412e
Create Date: 2024-05-16 20:22:56.107433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caafd3e9317a'
down_revision: Union[str, None] = '7c7431c1412e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'name')
    op.drop_column('Users', 'email')
    op.drop_column('Users', 'google_access_token')
    # ### end Alembic commands ###
